version: '2.1'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  postgres:
    hostname: postgres
    tmpfs:
      - /tmp
    build:
      dockerfile: Dockerfile
      context: bbtest/postgres
    healthcheck:
      test: pg_isready -U postgres -d openbank
      interval: 10s
      timeout: 3s
      retries: 10

  # -------------------------------------------------------------------------- #

  perf:
    image: docker.io/jancajthaml/bbtest:amd64
    environment:
      UNIT_ARCH: amd64
      GITHUB_RELEASE_TOKEN: ${GITHUB_RELEASE_TOKEN:-}
      CI: ${CI:-false}
    tmpfs:
      - /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/opt/app
    working_dir: /opt/app

  # -------------------------------------------------------------------------- #

  bbtest-amd64:
    image: docker.io/jancajthaml/bbtest:amd64
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      UNIT_ARCH: amd64
      GITHUB_RELEASE_TOKEN: ${GITHUB_RELEASE_TOKEN:-}
      CI: ${CI:-false}
    tmpfs:
      - /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/opt/app
    working_dir: /opt/app

  # -------------------------------------------------------------------------- #

  bbtest-arm64:
    image: docker.io/jancajthaml/bbtest:arm64
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      UNIT_ARCH: arm64
      GITHUB_RELEASE_TOKEN: ${GITHUB_RELEASE_TOKEN:-}
      CI: ${CI:-false}
    tmpfs:
      - /data
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/opt/app
    working_dir: /opt/app

  # -------------------------------------------------------------------------- #

  bbtest-armhf:
    image: docker.io/jancajthaml/bbtest:armhf
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      UNIT_ARCH: armhf
      GITHUB_RELEASE_TOKEN: ${GITHUB_RELEASE_TOKEN:-}
      CI: ${CI:-false}
    tmpfs:
      - /data
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/opt/app
    working_dir: /opt/app

# ---------------------------------------------------------------------------- #
