version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  perf:
    image: docker.io/jancajthaml/bbtest:${ARCH}
    tty: true
    environment:
      CI: ${CI:-false}
    tmpfs:
      - /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .:/opt/app:delegated
    working_dir: /opt/app

  # -------------------------------------------------------------------------- #

  bbtest:
    image: docker.io/jancajthaml/bbtest:${ARCH}
    tty: true
    environment:
      CI: ${CI:-false}
    tmpfs:
      - /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .:/opt/app:delegated
    working_dir: /opt/app

# ---------------------------------------------------------------------------- #
