version: '2'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  bbtest:
    build:
      context: .
      dockerfile: bbtest/Dockerfile
    image: e2e_dev
    working_dir: /opt/bbtest
    environment:
      - PERSISTENCE_PATH=/data
      - TENANT=test
      - COMPOSE_PROJECT_NAME
    volumes:
      - ./reports:/reports
      - logs:/logs
      - journal:/data
      - metrics:/metrics
      - ./bbtest:/opt/bbtest
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  # -------------------------------------------------------------------------- #

  lake:
    image: openbank/lake:master
    container_name: e2e_lake
    restart: "no"
    environment:
      - LAKE_LOG_LEVEL=DEBUG
    ports:
      - "5562"
      - "5561"
    logging:
      driver: json-file

  # -------------------------------------------------------------------------- #

  search:
    image: openbank/search:master
    restart: unless-stopped
    container_name: e2e_search
    environment:
      - SEARCH_HTTP_PORT=8080
      - SEARCH_LAKE_HOSTNAME=lake
      - SEARCH_MONGO_HOSTNAME=e2e_mongodb
      - SEARCH_TENANT=test
    ports:
      - "8080"
    logging:
      driver: json-file

  # -------------------------------------------------------------------------- #

  wall:
    image: openbank/wall:master
    restart: unless-stopped
    container_name: e2e_wall
    environment:
      - WALL_STORAGE=/data
      - WALL_LAKE_HOSTNAME=lake
      - WALL_LOG_LEVEL=DEBUG
      - WALL_METRICS_REFRESHRATE=1s
      - WALL_METRICS_OUTPUT=/metrics/metrics_bbtest_wall.json
    volumes:
      - journal:/data
      - metrics:/metrics
    ports:
      - "8080"
    logging:
      driver: json-file

  # -------------------------------------------------------------------------- #

  vault:
    image: openbank/vault:master
    container_name: e2e_vault_test
    restart: unless-stopped
    environment:
      - VAULT_STORAGE=/data
      - VAULT_LOG_LEVEL=DEBUG
      - VAULT_TENANT=test
      - VAULT_JOURNAL_SATURATION=1
      - VAULT_SNAPSHOT_SCANINTERVAL=1s
      - VAULT_LAKE_HOSTNAME=lake
      - VAULT_METRICS_REFRESHRATE=1s
      - VAULT_METRICS_OUTPUT=/metrics/metrics_bbtest_vault_test.json
    volumes:
      - journal:/data
      - metrics:/metrics
    logging:
      driver: json-file

  # -------------------------------------------------------------------------- #

  mongodb:
    image: mongo:latest
    restart: "no"
    container_name: e2e_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    entrypoint: ["mongod"]
    command: ["--smallfiles", "--logpath=/dev/null"]

# ---------------------------------------------------------------------------- #

volumes:

  journal:
    driver: local
  metrics:
    driver: local
  logs:
    driver: local
  mongo:
    driver: local

# ---------------------------------------------------------------------------- #
