version: '2'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  candidate:
    build:
      context: .
      dockerfile: Dockerfile
    image: openbankdev/e2e_candidate

  # -------------------------------------------------------------------------- #

  bbtest:
    build:
      context: .
      dockerfile: bbtest/Dockerfile
    image: e2e/bbtest
    working_dir: /opt/bbtest
    environment:
      - COMPOSE_PROJECT_NAME
    volumes:
      - ./reports:/reports
      - journal:/data
      - ./bbtest:/opt/bbtest
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  # -------------------------------------------------------------------------- #

  perf:
    build:
      context: .
      dockerfile: perf/Dockerfile
    image: e2e/perf
    working_dir: /opt/perf
    environment:
      - COMPOSE_PROJECT_NAME
    volumes:
      - ./reports:/reports
      - journal:/data
      - ./perf:/opt/perf
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  # -------------------------------------------------------------------------- #

  mongodb:
    image: mongo:latest
    restart: "no"
    container_name: e2e_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    entrypoint: ["mongod"]
    command: ["--smallfiles", "--logpath=/dev/null"]

# ---------------------------------------------------------------------------- #

volumes:

  journal:
    driver: local
  mongo:
    driver: local

# ---------------------------------------------------------------------------- #
