version: '2'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  candidate:
    build:
      context: .
      dockerfile: Dockerfile
    image: openbankdev/e2e_candidate

  # -------------------------------------------------------------------------- #

  bbtest:
    extends: candidate
    working_dir: /opt/bbtest
    environment:
      - COMPOSE_PROJECT_NAME
    volumes:
      - ./reports:/reports
      - ./bbtest:/opt/bbtest
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  # -------------------------------------------------------------------------- #

  perf:
    extends: candidate
    working_dir: /opt/perf
    environment:
      - COMPOSE_PROJECT_NAME
    volumes:
      - ./reports:/reports
      - ./perf:/opt/perf
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

# ---------------------------------------------------------------------------- #
