version: 2

################################################################################

workflows:

  version: 2

  commit:
    jobs:
      - performance
      - bbtest
      - report:
          requires:
            - performance
            - bbtest

  rolling_contract:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - bbtest
      - report:
          requires:
            - bbtest

  rolling_performance:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - performance
      - report:
          requires:
            - performance

################################################################################

jobs:

  ##############################################################################

  report:
    machine: true
    environment:
      - METRICS_PATH: /home/circleci/project/reports/metrics
    working_directory: /home/circleci/project

    steps:
      - attach_workspace:
          at: /home/circleci/project/reports
      - run:
          name: Regenerate reports
          command: |
            if [ ! -d ${METRICS_PATH} ] ; then
              exit 1
            fi

            git config --global user.email "jan.cajthaml@gmail.com"
            git config --global user.name "CircleCI e2e rolling update"

            git clone git@github.com:jancajthaml-openbank/health-check.git

            cp -r reports/metrics health-check/reports

            cd health-check

            python generate_metrics_report.py > README.md

            git add .
            git commit -am "circleci e2e rolling update of reports"
            git push

  ##############################################################################

  performance:
    machine: true
    environment:
      - PERSISTENCE_PATH: /home/circleci/project/data
      - LOGS_PATH: /home/circleci/project/logs
      - METRICS_PATH: /home/circleci/project/metrics
      - TENANT: performance
      - MAX_PARALLELISM: 10

    working_directory: /home/circleci/project

    steps:
      - checkout
      - run:
          name: Prepare performance tests
          command: |
            pull() {
              echo "pulling openbank/${1}:${RELEASE_BRANCH}"
              docker pull openbank/${1}:${RELEASE_BRANCH}
            }

            pull vault &
            pull lake &
            pull wall &
            wait

            cd perf && docker build -t e2e_perf .

            mkdir -p ${LOGS_PATH} ${PERSISTENCE_PATH} ${METRICS_PATH}
      - run:
          name: Run performance tests
          command: |
            rand_alnum() {
              LC_ALL=C tr -dc 'A-Z0-9' </dev/urandom | head -c 13 ; echo
            }

            calc() {
              echo "$*" | bc -l
            }

            spawn_queue() {
              name="queue_$1"

              docker run \
                -d \
                -h queue \
                -v ${LOGS_PATH}:/logs \
                -v ${METRICS_PATH}:/opt/metrics \
                --net=e2e_bridge \
                --net-alias=queue \
                --name=performance_queue_${name} \
                --publish 5562:5562 \
                --publish 5561:5561 \
              openbank/lake:master
            }

            spawn_wall() {
              name="wall_$1"

              docker run \
                -d \
                -h ${name} \
                -e HOSTNAME=${name} \
                -e WALL_LAKE_HOSTNAME=queue \
                -e WALL_STORAGE=/data \
                -e WALL_LOG_LEVEL=DEBUG \
                -e WALL_METRICS_REFRESHRATE=10s \
                -e WALL_METRICS_OUTPUT=/opt/metrics/metrics_perf_${name}.json \
                -v ${PERSISTENCE_PATH}:/data \
                -v ${LOGS_PATH}:/logs \
                -v ${METRICS_PATH}:/opt/metrics \
                --net=e2e_bridge \
                --net-alias=${name} \
                --name=performance_wall_${name} \
                --publish 8080:8080 \
              openbank/wall:master
            }

            spawn_vault() {
              name="vault_$1"

              docker run \
                -d \
                -h ${name} \
                -e VAULT_LAKE_HOSTNAME=queue \
                -e VAULT_STORAGE=/data \
                -e VAULT_LOG_LEVEL=DEBUG \
                -e VAULT_JOURNAL_SATURATION=10 \
                -e VAULT_SNAPSHOT_SCANINTERVAL=1s \
                -e VAULT_TENANT=${TENANT} \
                -e VAULT_METRICS_REFRESHRATE=10s \
                -e VAULT_METRICS_OUTPUT=/opt/metrics/metrics_perf_${name}.json \
                -v ${PERSISTENCE_PATH}:/data \
                -v ${LOGS_PATH}:/logs \
                -v ${METRICS_PATH}:/opt/metrics \
                --net=e2e_bridge \
                --net-alias=${name} \
                --name=performance_vault_${name} \
              openbank/vault:master
            }

            post_stop() {
              if [ -z $at_most_once ]; then
                echo ""

                at_most_once=true

                if [ -n $wall_container ] ; then
                  c=$wall_container
                  unset wall_container
                  docker kill $c &> /dev/null || :
                  echo "storing logs to ${LOGS_PATH}/perf_wall.log"
                  docker logs $c &> ${LOGS_PATH}/perf_wall.log
                  echo "deleting wall container $c"
                  docker rm -f $c &> /dev/null || :
                fi

                if [ -n $vault_container ] ; then
                  c=$vault_container
                  unset vault_container
                  docker kill $c &> /dev/null || :
                  echo "storing logs to ${LOGS_PATH}/perf_vault.log"
                  docker logs $c &> ${LOGS_PATH}/perf_vault.log
                  echo "deleting vault container $c"
                  docker rm -f $c &> /dev/null || :
                fi

                if [ -n $queue_container ] ; then
                  c=$queue_container
                  unset queue_container
                  docker kill $c &> /dev/null || :
                  echo "storing logs to ${LOGS_PATH}/perf_queue.log"
                  docker logs $c &> ${LOGS_PATH}/perf_queue.log
                  echo "deleting queue container $c"
                  docker rm -f $c &> /dev/null || :
                fi

                exit 0
              fi
            }

            trap post_stop EXIT

            docker network create e2e_bridge &> /dev/null || :

            queue_container=$(spawn_queue 1)

            if [ -z "$queue_container" ] ; then
              echo "failed to start queue"
              exit 1
            fi

            vault_container=$(spawn_vault 1)

            if [ -z "$vault_container" ] ; then
              echo "failed to start vault"
              exit 1
            fi

            wall_container=$(spawn_wall 1)

            if [ -z "$wall_container" ] ; then
              echo "failed to start wall"
              exit 1
            fi

            docker run \
              -t \
              -e LAKE_HOSTNAME=queue \
              -e HTTP_ENTRYPOINT=wall_1:8080 \
              -e TENANT=${TENANT} \
              -e MAX_PARALLELISM=${MAX_PARALLELISM} \
              -e TTY=${TTY} \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v ${PERSISTENCE_PATH}:/data \
              -v ${LOGS_PATH}:/logs \
              -v ${METRICS_PATH}:/opt/metrics \
              --net=e2e_bridge \
              e2e_perf
      - store_artifacts:
          path: /home/circleci/project/metrics
          destination: metrics
      - store_artifacts:
          path: /home/circleci/project/logs
          destination: logs
      - persist_to_workspace:
          root: .
          paths:
            - metrics
            - logs

  ##############################################################################

  bbtest:
    machine: true
    environment:
      - RELEASE_BRANCH: master

    working_directory: /home/circleci/project

    steps:
      - checkout
      - run:
          name: Prepare blackbox tests
          command: |
            pull() {
              echo "pulling openbank/${1}:${RELEASE_BRANCH}"
              docker pull openbank/${1}:${RELEASE_BRANCH}
            }

            pull vault &
            pull lake &
            pull wall &
            wait

            (docker rm -f $(docker-compose ps -q) 2> /dev/null || :) &> /dev/null

            docker-compose build bbtest
      - run:
          name: Run blackbox tests
          command: |
            VERSION=${RELEASE_BRANCH} \
              docker-compose run --rm bbtest

            if [ ! -d metrics ] || [ ! -d logs ] ; then
              exit 1
            fi

            # fixme count files in metrics and if empty exit 1

      - store_artifacts:
          path: /home/circleci/project/metrics
          destination: metrics
      - store_artifacts:
          path: /home/circleci/project/logs
          destination: logs
      - persist_to_workspace:
          root: .
          paths:
            - metrics
            - logs
      - run:
          name: Teardown blackbox tests
          command: |
            (docker rm -f $(docker-compose ps -q) 2> /dev/null || :) &> /dev/null
            (docker rm -f $(docker ps -aqf "name=bbtest") || :) &> /dev/null

################################################################################
