version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  commit:
    jobs:
      - performance-test:
          matrix:
            parameters:
              arch: [amd64, arm64]
      - blackbox-test:
          matrix:
            parameters:
              arch: [amd64, arm64]

  rolling_contract:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - blackbox-test:
          matrix:
            parameters:
              arch: [amd64, arm64]

  rolling_performance:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - performance-test:
          matrix:
            parameters:
              arch: [amd64, arm64]

# ---------------------------------------------------------------------------- #

executors:

  machine-arm64:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: false
      resource_class: arm.medium

  machine-amd64:
    machine:
      image: ubuntu-2004:202111-01
      docker_layer_caching: false
      resource_class: medium

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  blackbox-test:
    parameters:
      arch:
        type: string
    executor: machine-<< parameters.arch >>
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: docker --dns 208.67.222.222 pull docker.io/jancajthaml/bbtest:<< parameters.arch >>
      - run: docker-compose build postgres
      - run:
          name: Run blackbox tests << parameters.arch >>
          command: |
            export ARCH=<< parameters.arch >>
            docker-compose up -d bbtest
            docker exec -t $(docker-compose ps -q bbtest) python3 /opt/app/bbtest/main.py
            docker-compose down -v
          no_output_timeout: 5m
      - store_test_results:
          path: /home/circleci/project/reports/blackbox-tests/junit
      - store_artifacts:
          path: /home/circleci/project/reports/blackbox-tests
          destination: reports

  # -------------------------------------------------------------------------- #

  performance-test:
    parameters:
      arch:
        type: string
    executor: machine-<< parameters.arch >>
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: docker pull docker.io/jancajthaml/bbtest:<< parameters.arch >>
      - run:
          name: Run performance tests << parameters.arch >>
          command: |
            export ARCH=<< parameters.arch >>
            docker-compose up -d perf
            docker exec -t $(docker-compose ps -q perf) python3 /opt/app/perf/main.py
            docker-compose down -v
          no_output_timeout: 2h
      - store_artifacts:
          path: /home/circleci/project/reports/perf-tests
          destination: reports
      - persist_to_workspace:
          root: /home/circleci/project/reports/perf-tests
          paths:
            - metrics

# ---------------------------------------------------------------------------- #
