version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  commit:
    jobs:
      - performance-test-amd64
      - performance-test-arm64
      - blackbox-test-amd64
      - blackbox-test-arm64

  rolling_contract:
    triggers:
      - schedule:
          cron: "10,50 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - blackbox-test-amd64
      - blackbox-test-arm64

  rolling_performance:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - performance-test-amd64
      - performance-test-arm64

# ---------------------------------------------------------------------------- #

executors:

  testbed:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: false

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  blackbox-test-amd64:
    executor: testbed
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: docker system prune -f
      - run: docker pull docker.io/jancajthaml/bbtest:amd64
      - run: docker-compose build postgres
      - run:
          name: Run blackbox tests
          command: |
            export ARCH=amd64
            docker-compose up -d bbtest
            docker logs $(docker-compose ps -q bbtest)
            docker exec -t $(docker-compose ps -q bbtest) python3 /opt/app/bbtest/main.py
            docker-compose down -v
          no_output_timeout: 5m
      - store_test_results:
          path: /home/circleci/project/reports/blackbox-tests/junit
      - store_artifacts:
          path: /home/circleci/project/reports/blackbox-tests
          destination: reports

  # -------------------------------------------------------------------------- #

  blackbox-test-arm64:
    executor: testbed
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: docker system prune -f
      - run: docker pull docker.io/jancajthaml/bbtest:arm64
      - run: docker-compose build postgres
      - run:
          name: Run blackbox tests
          command: |
            export ARCH=arm64
            docker-compose up -d bbtest
            docker logs $(docker-compose ps -q bbtest)
            docker exec -t $(docker-compose ps -q bbtest) python3 /opt/app/bbtest/main.py
            docker-compose down -v
          no_output_timeout: 5m
      - store_test_results:
          path: /home/circleci/project/reports/blackbox-tests/junit
      - store_artifacts:
          path: /home/circleci/project/reports/blackbox-tests
          destination: reports

  # -------------------------------------------------------------------------- #

  performance-test-amd64:
    executor: testbed
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: docker system prune -f
      - run: docker pull docker.io/jancajthaml/bbtest:amd64
      - run:
          name: Run performance tests
          command: |
            export ARCH=amd64
            docker-compose up -d perf
            docker logs $(docker-compose ps -q bbtest)
            docker exec -t $(docker-compose ps -q perf) python3 /opt/app/perf/main.py
            docker-compose down -v
          no_output_timeout: 2h
      - store_artifacts:
          path: /home/circleci/project/reports/perf-tests
          destination: reports
      - persist_to_workspace:
          root: /home/circleci/project/reports/perf-tests
          paths:
            - metrics

  # -------------------------------------------------------------------------- #

  performance-test-arm64:
    executor: testbed
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: docker system prune -f
      - run: docker pull docker.io/jancajthaml/bbtest:arm64
      - run:
          name: Run performance tests
          command: |
            export ARCH=arm64
            docker-compose up -d perf
            docker logs $(docker-compose ps -q bbtest)
            docker exec -t $(docker-compose ps -q perf) python3 /opt/app/perf/main.py
            docker-compose down -v
          no_output_timeout: 2h
      - store_artifacts:
          path: /home/circleci/project/reports/perf-tests
          destination: reports
      - persist_to_workspace:
          root: /home/circleci/project/reports/perf-tests
          paths:
            - metrics

# ---------------------------------------------------------------------------- #
