kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transaction-journal-claim
  namespace: openbank
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
