kind: PersistentVolume
apiVersion: v1
metadata:
  name: vault-test-journal-volume
  namespace: openbank
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/vault/journal"
