kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-test-journal-claim
  namespace: openbank
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
