#!/bin/bash

#set -eo pipefail

################################################################################

VERSION=${VERSION:=latest}
LOG_LEVEL=${LOG_LEVEL:=ERROR}

if [ -z ${LOGS_PATH} ] ; then
  LOGS_PATH="$(pwd)/reports/perf_logs"
fi

if [ -z ${METRICS_PATH} ] ; then
  METRICS_PATH="$(pwd)/reports/perf_metrics"
fi

network=e2e_bridge

post_stop() {
  if [ -z $at_most_once ] ; then
    echo -en '\033[0m'

    at_most_once=true

    echo "deleting network $network"
    (docker network rm $network &> /dev/null || :)

    exit 0
  fi
}

################################################################################

trap exit INT TERM
trap post_stop EXIT

################################################################################

docker network create ${network} &> /dev/null || :

docker run \
  -it \
  -e LOG_LEVEL=${LOG_LEVEL} \
  -e VERSION=${VERSION} \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ${LOGS_PATH}:/logs \
  -v ${METRICS_PATH}:/opt/metrics \
  --net=${network} \
  e2e_perf

exit 0
